### ISSUE TITLE
Estimate the cost of using closed-source models on the Mediatree data

### ISSUE THREAD

**Issue by ycrouin** [dataforgoodfr/climateguard#11]
Count the number of tokens in the Mediatree data located at https://drive.google.com/drive/folders/1d0idkOmMIXabj7ajYhvkitMMHnH_woSN, and estimate the cost of running the detection pipeline on the entire dataset using closed-source LLMs.

Is this solution scalable? Should we consider using SLM to filter data more aggressively than by relying solely on the keyword-based filters from the QuotaClimate Observatoire?

**Comment by fraboniface** [comment]
Before we have the full data, here is a back-of-the-envelope calculation.

The canvas on Slack mentions 19 channels for 800 hours (each I guess). That would be 19 x 800 = 15,200 h = 456,000 2-min-samples. Assuming 1000 tokens per sample (to check, but I remember @TheoLvs citing something like that), that would amount to 456,000,000 total input tokens or $68.40 at current GPT4o-mini pricing ($0.15/1M it). Output tokens are 4x more expensive, but we have a lot more control over those by being smart about the output we ask of the model. Related to #7.

So the whole thing could turn out to be pretty cheap.
