### ISSUE TITLE
Define our contrarian claims taxonomy

### ISSUE THREAD

**Issue by ycrouin** [dataforgoodfr/climateguard#7]
Define our contrarian claims taxonomy.
We can reuse the CARDS taxonomy or come up with our own.

![cards_taxonomy](https://github.com/user-attachments/assets/d18d1802-a7f2-4a54-a5af-b2a46f846cc5)

_Note: See [here](https://data-for-good.slack.com/archives/C07PNKP8Q03/p1729783899108279) for an update on the CARDS taxonomy_

# Definition Of Done

We have a list of classes and their defintion.

_To get started, maybe we could start simple, only with the "Level 1" from the CARDS taxonomy?_

**Comment by fraboniface** [comment]
Agreed, we can go for level 1 oniy but give it the full taxonomy in the context as few-shot examples. To save on output tokens, we could also only ask the model to output a number like 0 -> none and 1-5 -> corresponding CARDS category.
